### ISSUE TITLE
Add some documentation about how to add more datasets

### ISSUE THREAD

**Issue by tordans** [plepe/ogd-wikimedia-osm-checker#10]
We have a few datasets in Berlin, that I would love to compare with a tool like this. If possible, please extend the documentation about how to add other datasets. Maybe that could be the topic of the next screencast? :-).

Thanks for the tool!

**Comment by plepe** [comment]
I will work on some documentation. Stay tuned!

**Comment by plepe** [comment]
You could start with creating a ruleset which extracts data from wikipedia lists (if there are any) for the [wikipedia-list-extractor](https://github.com/plepe/wikipedia-list-extractor) module.

This is also used by the checker.

**Comment by plepe** [comment]
There's this nice demo app for wikipedia-list-extractor: https://openstreetmap.at/demo-wikipedia-list-extractor/
(Source: https://github.com/plepe/demo-wikipedia-list-extractor)

**Comment by plepe** [comment]
I just re-structured the code to make it easier to understand and created docu. It has not been thoroughly tested yet, so it's not yet on the main branch:
https://github.com/plepe/ogd-wikimedia-osm-checker/blob/restructure/Dataset.md

Please tell me if you can work with this :-)

**Comment by plepe** [comment]
I decided to convert the dataset definition to YAML, it's much easier this way. I think the branch is almost ready, I hope to merge it to master soon.

-> new branch: 'yaml'
https://github.com/plepe/ogd-wikimedia-osm-checker/blob/yaml/README.md
https://github.com/plepe/ogd-wikimedia-osm-checker/blob/yaml/example.md
https://github.com/plepe/ogd-wikimedia-osm-checker/blob/yaml/minimal.md

A very simple dataset is this:
https://github.com/plepe/ogd-wikimedia-osm-checker/blob/yaml/datasets/wiener-toiletten.yaml

I'll try to make a screencast tomorrow!

**Comment by plepe** [comment]
It took a while longer, but finally it's done! https://www.youtube.com/watch?v=4PKUCjS2HL8

**Comment by plepe** [comment]
I now even added the "Denkmalliste Berlin" dataset to the application: https://www.openstreetmap.at/checker/#denkmalliste-berlin .

I used more or less the same recommended wikidata properties and openstreetmap tags: https://github.com/plepe/ogd-wikimedia-osm-checker/blob/master/datasets/denkmalliste-berlin.yaml

This is the download function (as mentioned in the screencast, I had to modify the IDs in the CSV file, because the leading '0' is missing): https://github.com/plepe/ogd-wikimedia-osm-checker/blob/master/src/datasets/DownloadDenkmallisteBerlin.js

**Comment by plepe** [comment]
I think, this has been successfully done, so I'll close that issue.
